/* eslint-disable sort-keys */

const path = require('path');
const webpack = require('webpack');
const HtmlWebpackPlugin = require('html-webpack-plugin');
const webpackMerge = require('webpack-merge');

const aliases = require('./build-utils/aliases');
const presetConfig = require('./build-utils/loadPresets');
const modeConfig = (env) => require(`./build-utils/webpack.${env}`)(env); // eslint-disable-line

module.exports = ({
  mode = 'production',
  presets = ['babel', 'css', 'svg'],
}) => (
  webpackMerge.merge(
    {
      mode,
      entry: {
        'src/index.jsx': [
          path.join(__dirname, './src/index.jsx'),
        ],
      },
      resolve: {
        alias: aliases,
        extensions: ['*', '.js', '.jsx'],
      },
      output: {
        chunkFilename: '[name].lazy-chunk.js',
        filename: 'bundle.[hash].js',
        path: path.resolve('dist'),
        publicPath: mode === 'production' ? './' : '/',
      },
      plugins: [
        new HtmlWebpackPlugin({
          inject: true, // Inject all files that are generated by webpack
          template: './public/index.html',
        }),
        new webpack.ProgressPlugin(),
      ],
    },
    modeConfig(mode),
    presetConfig({ mode, presets }),
  )
);
